### ISSUE TITLE
Help Sending Information to Amazon for config

### ISSUE THREAD

**Issue by ryanlaux** [auchter/haaska#1]
Currently on the setup step to email amazon for provisioning, but not sure what to report for the Oauth section while using Login with Amazon. Is the Auth info somewhere on login with amazon?

**Comment by auchter** [comment]
Yes, it is. Since it's been a few months, and unfortunately I didn't take great notes at the time, I'm not sure if this is exactly accurate but hopefully it'll get you started:

Sign up for Login with Amazon and register a new application
Go to: https://sellercentral.amazon.com/gp/homepage.html and login if necessary
Hopefully there you'll see a dashboard that shows you some fields like "Client ID" and "Client Secret", which are the relevant pieces of information for the Oauth section:

OAuth Client ID: <your client id>
OAuth Client Secret: <your client secret>
OAuth Scope: profile
OAuth authorization URL: https://www.amazon.com/ap/oa
OAuth token URL: https://api.amazon.com/auth/o2/token 

Let me know if that helps.

**Comment by ryanlaux** [comment]
<img width="982" alt="screen shot 2016-02-22 at 11 49 21 pm" src="https://cloud.githubusercontent.com/assets/6530603/13242069/1488ee94-d9bf-11e5-9861-1c18c94f2b0e.png">
This look accurate?

**Comment by auchter** [comment]
Indeed, looks good to me. Hopefully Amazon agrees ;)

**Comment by ryanlaux** [comment]
Sweet! I'll submit and hopefully they approve. Did you have to setup a skill or anything on the Alexa dev center?

**Comment by ryanlaux** [comment]
Also how much memory do you specify for the lambda function? I have it set to 128 mb and 3 second timeout from defaults

**Comment by ryanlaux** [comment]
So I was able to get provisioned and the adapter shows up in my app! But it doesn't seem to control anything yet, do I have to do anything else or should it just work ?

**Comment by ryanlaux** [comment]
Sorry for bombarding you with messages.. Just excited to get this working soon! I was able to figure out the authentication and enable it in the app, but i'm getting an error in the lambda test console. I'm getting a Key Error message and not sure what to do about it. If you have any ideas let mw know!

`
{
  "stackTrace": [
    [
      "/var/task/haaska.py",
      42,
      "event_handler",
      "name = event['header']['name']"
    ]
  ],
  "errorType": "KeyError",
  "errorMessage": "'header'"
}
`

**Comment by auchter** [comment]
> So I was able to get provisioned and the adapter shows up in my app! But it doesn't seem to control anything yet, do I have to do anything else or should it just work ?

After getting it provisioned and enabling it in the Alexa app, you should be able to say "Alexa, discover my devices" in order to contact your Home Assistant instance and discover entities.

> I'm getting a Key Error message and not sure what to do about it. If you have any ideas let mw know!

That's probably because the test event you're sending is either empty or malformed. Try changing the event to:
```
{
  "header": {
    "payloadVersion": "1",
    "namespace": "Control",
    "name": "DiscoverAppliancesRequest"
  },
  "payload": {
      "accessToken": "whatever"
  }
}
```
instead. If everything goes well, you should see something along the lines of:
```
{
  "header": {
    "payloadVersion": "1",
    "namespace": "Discovery",
    "name": "DiscoverAppliancesResponse"
  },
  "payload": {
    "discoveredAppliances": [
      {
        "modelName": "Unknown",
        "friendlyDescription": "Hanging",
        "version": "Unknown",
        "additionalApplianceDetails": {
          "entity_id": "light.hanging_level_2",
          "dimmable": true
        },
        "manufacturerName": "Unknown",
        "friendlyName": "Hanging",
        "applianceId": "08837cb7e57952cbde1162aca7bd64a7f6450d55",
        "isReachable": true
      }
}
```
under the "Execution result"

**Comment by ryanlaux** [comment]
Ahh didn't realized you had to add a test event. Just did that and I can control my HA events flawlessly! Thank you!

**Comment by auchter** [comment]
Awesome! Glad to hear you got it working!

**Comment by shashishd** [comment]
I get following error when I run the test:
{
  "errorMessage": "2017-01-28T09:25:43.675Z bb190910-e53b-11e6-b69d-73a6bbd86272 Task timed out after 5.00 seconds"
}

**Comment by intrawit** [comment]
i get the same

**Comment by ryanlaux** [comment]
Any reason you guys aren't now using the built in emulated hue component to connect HA to Alexa?

**Comment by intrawit** [comment]
Where can I get the emulated hue?

**Comment by ryanlaux** [comment]
Its built in to the newest version of home assistant! More info is on the Alexa page for home assistant : https://home-assistant.io/components/alexa/

**Comment by shadow05139** [comment]
hi im having an issue with my lambda function saying "type object 'allowed' has no attribute 'Control'" please help...

**Comment by MACscr** [comment]
@auchter I am trying out your test function and I get the same error as @shadow05139:

```{
  "errorMessage": "type object 'allowed' has no attribute 'Control'",
  "errorType": "AttributeError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      668,
      "event_handler",
      "ha, payload)"
    ],
    [
      "/var/task/haaska.py",
      294,
      "invoke",
      "obj = make_class(allowed)(namespace, name, ha, context)"
    ]
  ]
}```

**Comment by shadow05139** [comment]
What's the name of your haaska function as that was my error.

On 13/02/2018 9:16 AM, Mark Chaney <notifications@github.com> wrote:

@auchter<https://github.com/auchter> I am trying out your test function and I get the same error as @shadow05139<https://github.com/shadow05139>:

  "errorMessage": "type object 'allowed' has no attribute 'Control'",
  "errorType": "AttributeError",
  "stackTrace": [
    [
      "/var/task/haaska.py",
      668,
      "event_handler",
      "ha, payload)"
    ],
    [
      "/var/task/haaska.py",
      294,
      "invoke",
      "obj = make_class(allowed)(namespace, name, ha, context)"
    ]
  ]
}```

**Comment by MACscr** [comment]
haaska

- Mark

**Comment by shadow05139** [comment]
Im having this issue again on another setup defiantly is not the name of the function 

this is the log output any help would be much appreciated

START RequestId: 82a7da3d-d98b-11e8-9acf-9f48e46f5bf5 Version: $LATEST
type object 'allowed' has no attribute 'Control': AttributeError
Traceback (most recent call last):
  File "/var/task/haaska.py", line 668, in event_handler
    ha, payload)
  File "/var/task/haaska.py", line 294, in invoke
    obj = make_class(allowed)(namespace, name, ha, context)
AttributeError: type object 'allowed' has no attribute 'Control'

END RequestId: 82a7da3d-d98b-11e8-9acf-9f48e46f5bf5
REPORT RequestId: 82a7da3d-d98b-11e8-9acf-9f48e46f5bf5	Duration: 1.22 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB
