### ISSUE TITLE
Error on skill enable

### ISSUE THREAD

**Issue by boorsteinhome** [auchter/haaska#23]
When I try to enable the skill on the Alexa app it directs me to an amazon error webpage : 
Login With Amazon 
-An error occurred when we tried to process your request.

I've run the test on the Lambda console.  It comes back okay.  
I've followed the instructions on the Alexa avs github issues ( https://github.com/amzn/alexa-avs-raspberry-pi/issues/5).

Any ideas?  What info would you all need to help me fix this?

**Comment by technicalpickles** [comment]
I ran into this too. There should be a "More Details" link on that page. For me, I missed this step:

> Go back to Login with Amazon and enter the "Redirect URL" as an "Allowed Return URL" for the application you registered.

**Comment by boorsteinhome** [comment]
So, I went through all the steps again making a new skill.  And this time it worked.  I've compared the two skills and lambda functions and they appear to be exactly the same.  What ever the issue was I can't help anyone else.  Sorry.
