### ISSUE TITLE
Migrate to Smart Home Skill

### ISSUE THREAD

**Issue by stjohnjohnson** [auchter/haaska#4]
Looks like they changed everything: https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/steps-to-create-a-smart-home-skill

_note_ I'll try to look into this myself in the coming weeks, but I figured I'd let you know.

**Comment by auchter** [comment]
I actually updated haaska to use the new API last night. Note that you'll have to recreate the skill using the instructions in the README if you previously registered it via the manual email-Amazon process (since skills provisioned back then will only send the v1 requests to the skill adapter)
