### ISSUE TITLE
Alexa Smart Home Skills support setting colors of bulbs now

### ISSUE THREAD

**Issue by maddox** [auchter/haaska#44]
https://developer.amazon.com/public/solutions/alexa/alexa-skills-kit/docs/smart-home-skill-api-reference

**Comment by robbiet480** [comment]
#37

**Comment by maddox** [comment]
lol always got my back 

![](https://media4.giphy.com/media/xTiN0BXm4xA5hIUS8o/200w.gif)

I forgot to check pulls first. And now I don't have to do this, this weekend!!

**Comment by trisk** [comment]
#37 has been merged, this can be closed.
