### ISSUE TITLE
Changelog incorrect

### ISSUE THREAD

**Issue by robbiet480** [auchter/haaska#48]
Changelog says this:

> Entities hidden in Home Assistant (via the hidden attribute) are now hidden from haaska

But #40 was not merged, nor can I find the `hidden` attribute anywhere in source.

**Comment by trisk** [comment]
Yeah, only `haaska_hidden` is checked. The changelog is also missing climate domain support.

**Comment by robbiet480** [comment]
Fixed, thanks @auchter
