### ISSUE TITLE
Trouble setting up haaska

### ISSUE THREAD

**Issue by jonohunt** [auchter/haaska#68]
I've followed the instructions here, and the [YouTube video](https://www.youtube.com/watch?v=zZuwQ9spPkQ).

After checking, tweaking etc. I've managed to get the skill to show up in the Amazon Alexa app/website and successfully enable it, but it doesn't find anything after I've clicked on 'Discover Devices'.

Everything seems fine at developer.amazon.com and login.amazon.com, but at aws.amazon.com if I run a test (the one provided here) it shows the following log:

```
{
  "stackTrace": [
    [
      "/var/task/haaska.py",
      647,
      "event_handler",
      "config = Configuration('config.json')"
    ],
    [
      "/var/task/haaska.py",
      612,
      "__init__",
      "self._json = json.load(f)"
    ],
    [
      "/usr/lib64/python2.7/json/__init__.py",
      291,
      "load",
      "**kw)"
    ],
    [
      "/usr/lib64/python2.7/json/__init__.py",
      339,
      "loads",
      "return _default_decoder.decode(s)"
    ],
    [
      "/usr/lib64/python2.7/json/decoder.py",
      364,
      "decode",
      "obj, end = self.raw_decode(s, idx=_w(s, 0).end())"
    ],
    [
      "/usr/lib64/python2.7/json/decoder.py",
      380,
      "raw_decode",
      "obj, end = self.scan_once(s, idx)"
    ]
  ],
  "errorType": "ValueError",
  "errorMessage": "Expecting property name: line 4 column 1 (char 87)"
}
```

Does this make sense to anyone as to what the problem could be?

**Comment by trisk** [comment]
There appears to be a formatting error in your `config.json`

**Comment by jonohunt** [comment]
That's it, I'd made a mistake in config.json!

Thanks!
