### ISSUE TITLE
Giving haaska/Alexa some 'personality'?

### ISSUE THREAD

**Issue by jonohunt** [auchter/haaska#69]
For the ['other' Home Assistant Alexa skill](https://home-assistant.io/components/alexa/#giving-alexa-some-personality) you can 'give Alexa some personality' by adding various different replies from Alexa once it's activated something for you (instead of just saying OK).

Is it possible to do that with this skill? I don't know much about this, but it would be nice to have different replies instead of just 'OK' all the time.

**Comment by trisk** [comment]
We cannot define any utterances for the API based skills.

**Comment by jonohunt** [comment]
Ah, OK. Thanks for letting me know.
