### ISSUE TITLE
Struggling to Get This Installed

### ISSUE THREAD

**Issue by brusc** [auchter/haaska#7]
Not an issue so much with Haaska, but rather the instructions for installation. The steps for creating an AWSlamba function appear to have changed. There is no way to enable account linking or to enable an event source unless I'm something. :(

**Comment by atomicpapa** [comment]
I too am struggling with this.  It appears that the change from the Alexa Lighting API to the Smart Home Skill API has changed the installation procedure.

**Comment by brusc** [comment]
Still struggling through this. After going for a few hours, I appear to have my lamba service up correctly. It is communicating with Home Assistant. My skill also is made. The symptom is that my echo does not appear to "see" the skill or discover any of the home assistant devices. Got any ideas? :(

**Comment by brusc** [comment]
Got it figured out. Definitely a bit of a struggle. My skill only showed up when I searched for it - duh. Thanks for your work on this.

**Comment by brusc** [comment]
After more struggling to get an encrypted connection setup, I found that I was unable to use AWS with DuckDNS. When I used my direct public IP address everything worked great.

**Comment by mattsahn** [comment]
Mine is working now with DuckDNS, btw.

**Comment by longunmin** [comment]
How did you get it working with DuckDNS? I am getting a connection error when I try to use DuckDNS (local host too though)

**Comment by mattsahn** [comment]
Here's what my node code running on AWS looks like if that helps.


var http = require('http');
const AWS = require('aws-sdk');

exports.handler = (event, context, callback) => {
    console.log('Received event:', event.clickType, event.serialNumber, event.batteryVoltage);
    console.log('Done processing response.');

//setup REST call to my raspberry Pi via static DNS    
var options = {
  host: 'xxxxx.duckdns.org',
  port: 8123,
  path: '/api/events/dash_button_pressed_' + event.clickType,
  method: 'POST'
};

http.request(options, function(res) {
  console.log('STATUS: ' + res.statusCode);
  console.log('HEADERS: ' + JSON.stringify(res.headers));
  res.setEncoding('utf8');
  res.on('data', function (chunk) {
    console.log('BODY: ' + chunk);
  });
}).end();

**Comment by mattsahn** [comment]
Actually that's code from another project.  For haaska, the only thing I did was this config:

{
    "ha_url": "http://xxxxxx.duckdns.org:8123/api",
    "ha_passwd": ""
}

**Comment by longunmin** [comment]
Thank you @mattsahn! I've been told that Alexa skills require SSL, and it's looking at the wrong port. I'm going to try and encrypt and see how that goes

**Comment by mattsahn** [comment]
Yeah, you have to setup the authentication for the skill to work.  I followed the steps in this youtube guide exactly: https://youtu.be/zZuwQ9spPkQ
