### ISSUE TITLE
Haaska utterance to 'turn off'

### ISSUE THREAD

**Issue by mattmickeyj** [auchter/haaska#71]
I have 2 switches in HA called 'Kitchen Sonos' and 'Living Room Sonos' which runs the following commands (the below is for Kitchen Sonos):

command_on: "socos play 192.168.0.11"
command_off: "socos pause 192.168.0.11"

The full switch section in configuration.yaml is:

switch:
  platform: command_line
  switches:
    spartacus_control:
      command_on: "castnow --address 192.168.0.19 --command space --exit"
      command_off: "castnow --address 192.168.0.19 --command space --exit"
      friendly_name: Chromecast
    kitchen_sonos:
      command_on: "socos play 192.168.0.11"
      command_off: "socos pause 192.168.0.11"
      friendly_name: Kitchen Sonos
    living_room_sonos:
      command_on: "socos play 192.168.0.12"
      command_off: "socos play 192.168.0.12"
      friendly_name: Living Room Sonos

The devices appear in the Alexa app under Smart Home > Devices and the value friendly_name: Kitchen Sonos shows the device as 'Kitchen Sonos'  I can tell alexa to 'Turn on Kitchen Sonos' and it plays, but cannot say 'Turn off Kitchen Sonos', 'Stop Kitchen Sonos' or any of the other _off_ commands.  Running 'socos pause 192.168.0.11' from an ssh session pauses it instantly, as expected.  In the Alexa app under History, I can see the 'Turn off Kitchen Sonos' phrase being recorded, but it doesn't do anything.

Any assistance, would be greatly appreciated.

Many thanks in advance.
Matt

**Comment by trisk** [comment]
Did you test the turn_off service call for your entity directly?
Also, check the haaska logs from your Lambda settings.

**Comment by mattmickeyj** [comment]
My typo.  Apologies.
