### ISSUE TITLE
Minimum steps for changing Home Assistant / haaska password

### ISSUE THREAD

**Issue by tinstep** [auchter/haaska#73]
I have set an easy api password in HA, and now that I have this skill working and HA is exposed to the world, I think it best to change it - however it took me a while to get haaska up and running so just wanted to run the steps past you first. 
I looked at the code in the Lamda function on AWS, but couldn't find it any where so i figure i need to re-upload a zip.
Can you please confirm the steps needed to change the HA password and have haaska continue to work?

1. change the api-password in the configuration.yaml in HA
2. change the password in haaska/config/config.json
3. make
4. Upload and overwrite the zip file in the lambda.
job done.

**Comment by auchter** [comment]
The steps you've listed are correct. The zip file generated by `make` contains the config.json which controls the password used by haaska to talk to your HA instance.
