### ISSUE TITLE
Add __init__.py

### ISSUE THREAD

**Issue by robbiet480** [auchter/haaska#82]
In case haaska is used as an external package or as part of another Lambda...

**Comment by auchter** [comment]
I like the foreshadowing here... ;)

But yeah, feel free to open a pull request to add one.

**Comment by robbiet480** [comment]
[Lil more than foreshadowing at this point](https://github.com/auchter/haaska/issues/65#issuecomment-309927710) haha

Now that I think about this though, I may not do it. The only reason _to_ do it is silencing PyLint `no-name-in-module` errors at the cost of making it a bit harder for users to get started since I would probably end up really Pythonizing the whole thing (setup.py etc). So i'll hold off for now.

**Comment by robbiet480** [comment]
@auchter While I have you, can you reach out to me on the Home Assistant [Discord](https://discord.gg/pjHarw) or Twitter or email or something? Not sure how to get a hold of you privately.

**Comment by auchter** [comment]
@robbiet480 The email used in my commits is the best way to reach me: a@phire.org
