### ISSUE TITLE
changed from amazon.com account to amazon.co.uk and now haaska isn't working

### ISSUE THREAD

**Issue by mattmickeyj** [auchter/haaska#85]
As per the title - I have converted my account from a co.uk account to .coma and now haaska isn't working when running make test from the cli I get:

An error occurred (UnrecognizedClientException) when calling the Invoke operation: The security token included in the request is invalid.

In AWS the location is still set to North Virginia.

**Comment by mattmickeyj** [comment]
Apologies, running sudo make test returned:

{
  "header": {
    "payloadVersion": "2",
    "namespace": "Alexa.ConnectedHome.System",
    "name": "HealthCheckResponse",
    "messageId": "f696eb56-24ea-40b5-b21f-e25b8a52377c"
  },
  "payload": {
    "isHealthy": true
  }
}

So, it seems to be ok, but Alexa is not discovering any devices - switching my account back to a .com discovers all of my devices again.

**Comment by redstar2k1** [comment]
If your account is set to Uk, try moving your Lambda function to Ireland and it should work.

**Comment by mattmickeyj** [comment]
That worked a treat - thank you.

For anyone who comes across this issue, the below are the steps I took:

Convert your amazon.com account to amazon.co.uk
Remake the Lambda function in UK (Ireland) - copy the new ARN to your Alexa Skill [Alexa Skill > Configuration > Endpoint > untick North America and tick Europe.  Paste your new ARN in to the field].
