### ISSUE TITLE
Alexa won't discover any devices

### ISSUE THREAD

**Issue by goaluf** [auchter/haaska#99]
I've completed the setup of haaska following the guide outlined here, and by following the bruh videoguide as well.

I have successfully linked the haaska skill in the Alexa app. The Lambda function is successful when testing, and returns the mediaplayers and switch configured in HA.

The media players and switch is working as expected from the HA WebUI. However, when i run "Discover devices" in the Alexa app, none of the configured mediaplayers or switch are discovered by Alexa.

Did anyone encounter the same issue? Do i need to setup anything in HA, for Alexa to be able to discover the devices?

The only thing i can think off, is that maybe there's some issue with the account linking? Do i need to have my developer account address matching the Lambda aws server somehow? For now, the Lambda aws server is set to N. Virginia (Following bruhs example) and i've entered a dummy address for virginia in my developer account (I live in Denmark). But 'm still not able to discover any devices.

Here's the output from the Lambda test:

{
  "header": {
    "payloadVersion": "2",
    "namespace": "Alexa.ConnectedHome.Discovery",
    "name": "DiscoverAppliancesResponse",
    "messageId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  },
  "payload": {
    "discoveredAppliances": [
      {
        "modelName": "Unknown",
        "actions": [
          "turnOn",
          "turnOff",
          "setPercentage",
          "incrementPercentage",
          "decrementPercentage"
        ],
        "friendlyDescription": "Home Assistant Media Player",
        "version": "Unknown",
        "additionalApplianceDetails": {
          "entity_id": "media_player.playstation_4",
          "supported_features": 6528
        },
        "manufacturerName": "Unknown",
        "friendlyName": "Playstation 4",
        "applianceId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "isReachable": true
      },
      {
        "modelName": "Unknown",
        "actions": [
          "turnOn",
          "turnOff"
        ],
        "friendlyDescription": "Home Assistant Switch",
        "version": "Unknown",
        "additionalApplianceDetails": {
          "entity_id": "switch.playstation4",
          "supported_features": 0
        },
        "manufacturerName": "Unknown",
        "friendlyName": "Playstation 4",
        "applianceId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        "isReachable": true
      }
    ]
  }
}
Summary

**Comment by goaluf** [comment]
I was able to solve the issue by following https://github.com/auchter/haaska/issues/91 which stated that the alexa skill should be running with payload v2 instead of v3

**Comment by master-kenobi** [comment]
I cannot select V2. Only v3
